[package]
name = "advent"
version = "0.1.0"
authors = ["charwood"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.1.0"
regex = "1.7.0"
lazy_static = "1.4.0"

[profile.release]
debug = true
